### ISSUE TITLE
Superior full set crashes the game

### ISSUE THREAD

**Issue by MasterZitron** [AlephInfinity1/ForgeBlock#18]
Crash log: https://paste.ee/p/26nbv
Tested out the other sets, they all work fine. Only Superior causes the game to crash

Unrelated(?): Log file is being constantly spammed with ```[Render thread/INFO] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL debug message, id=1284, source=API, type=ERROR, severity=HIGH, message=GL_STACK_UNDERFLOW error generated. Attribute stack underflow.```

**Comment by MasterZitron** [comment]
Bump


Crash log :

```
[m[32m[16:08:01] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// You're mean.

Time: 6/12/22 4:08 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at alephinfinity1.forgeblock.item.armor.SuperiorDragonArmorItem.onLivingUpdate(SuperiorDragonArmorItem.java:65) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_49_SuperiorDragonArmorItem_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:316) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2023) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.forgeblock.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.forgeblock.json:AccessorPlayerEntity,pl:mixin:APP:mixins.forgeblock.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:235) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:196) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1398) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.57-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at alephinfinity1.forgeblock.item.armor.SuperiorDragonArmorItem.onLivingUpdate(SuperiorDragonArmorItem.java:65)
	at net.minecraftforge.eventbus.ASMEventHandler_49_SuperiorDragonArmorItem_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:316)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2023)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:235)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 139
	Entity Name: Zitronbtw
	Entity's Exact location: -153.24, 5.00, 48.26
	Entity's Block location: World: (-154,5,48), Chunk: (at 6,0,0 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:196)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Zitronbtw'/139, l='MpServer', x=-153.24, y=5.00, z=48.26]]
	Chunk stats: Client Chunk Cache: 625, 418
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 5936892827775699734
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-160,4,16), Chunk: (at 0,0,0 in -10,1; contains blocks -160,0,16 to -145,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 151109 game time, 1083 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976923504 bytes (931 MB) / 1760559104 bytes (1679 MB) up to 3698851840 bytes (3527 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3968m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.57-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.57-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.57-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.57-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.15.2_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.57-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.57
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.57-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.57-universal.jar Forge {forge@31.2.57 DONE}
		forgeblock-1.0.jar ForgeBlock Mod {forgeblock@1.0 DONE}
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 730M/PCIe/SSE2 GL version 4.6.0 NVIDIA 425.31, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 425.31
	OpenGlRenderer: GeForce GT 730M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[m[32m[16:08:01] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: #@!@# Game crashed! Crash report saved to:
```
